### ISSUE TITLE
Error when running jest v19 with jest-exponent

### ISSUE THREAD

**Issue by hafizio** [exponent/jest-exponent#5]
```
 FAIL  __tests__/app.test.js
  ● Test suite failed to run

    /Users/hafiz/pc/sample_app/node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:19
    type ModuleConfig = [
         ^^^^^^^^^^^^
    SyntaxError: Unexpected identifier

      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:320:12)
      at Object.<anonymous> (node_modules/jest-exponent/src/setup.js:60:27)
```

`yarn test` works fine when I remove the `preset: jest-exponent` option in the package.json.

Thanks!

**Comment by ecstasy2** [comment]
I am getting the same issue.
@hafizio were you able to find a fix for this?

**Comment by hafizio** [comment]
@ecstasy2 I ended up just using the `jest` package without depending on the `jest-exponent` package.

**Comment by jhhayashi** [comment]
I had same issue, fixed by using `jest-react-native` instead of `jest-exponent`

**Comment by alxyuu** [comment]
jest 19 ignores `preprocessorIgnorePatterns`. according to @brentvatne, it should be updated once 0.3.0 is released. in the meantime, you can add this inside the `jest` section of your `package.json`:

```
"transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|expo|@expo/*|exponent|@exponent/*)"
    ]
```

**Comment by dikaiosune** [comment]
v0.3.0 has been released -- if this still occurs with the new package please reopen

**Comment by kay-is** [comment]
Can't get it working.

I get `SyntaxError: Unexpected token import` in my own source files when I use this config:

    "jest": {
      "preset": "jest-expo"
    },


I get `SyntaxError: Unexpected identifier` on `type ModuleConfig = [` in the `react-native` files when I use this config:

    "jest": {
      "preset": "jest-expo",
      "transformIgnorePatterns": [
        "/node_modules/",
        "/src/"
      ]
    },

I get `SyntaxError: Unexpected token import` on a react-native import in the expo package when I use this config:

    "jest": {
      "preset": "react-native"
    },

I get `SyntaxError: Unexpected token )` in the react-native packages jest setup when I use this config:

    "jest": {
      "preset": "react-native",
      "transformIgnorePatterns": [
        "/node_modules/",
        "/src/"
      ]
    },
